export enum TypeQuery {
  DetailDocument = "DetailDocument",
  WorkSpaceCol = "WorkSpaceCol",
  CreateWorkItem = "CreateWorkItem",
  ListBoard = "ListBoard",
  CreateBoard = "CreateBoard",
  CreateList = "CreateList",
  UpdateBoard = "UpdateBoard",
  UpdateCard = "UpdateCard",
  DeleteList = "DeleteList",
  DeleteCard = "DeleteCard",
  UpdateCardInfo = "UpdateCardInfo",
  SearchChat = "SearchChat",
  UpdateInfo = "UpdateInfo",
}
